name: Build service image
description: |
  Build and publish a PlaceOS service image.

inputs:
  context:
    description: 'Build context for use by docker'
    required: true
  name:
    description: 'Service name'
    required: true
  tag:
    description: 'Version tag'
    required: true
  commit:
    description: 'PlaceOS release commit sha'
    required: true

outputs:
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}

runs:
  using: composite
  steps:
  - name: Set up QEMU
    uses: docker/setup-qemu-action@v1
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1
# - name: Login to DockerHub
#   uses: docker/login-action@v1
#   with:
#     username: ${{ secrets.DOCKERHUB_USERNAME }}
#     password: ${{ secrets.DOCKERHUB_TOKEN }}
  - name: Build and push
    id:   build
    uses: docker/build-push-action@v2
    with:
      context: ${{ inputs.context }}
      # push: true
      tags: placeos/${{ inputs.name }}:${{ inputs.tag }}
      build-args: PLACE_COMMIT=${{ inputs.commit }}
