name: Build

on:
  # Tempory manual dispatch for testing
  workflow_dispatch:
    inputs:
      version:
        description: 'Platform Version'
        required: true

jobs:
  platform-info:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.introspect.outputs.services }}
    steps:
    - id: checkout
      uses: actions/checkout@v2
    - id: introspect-services
      run: |
        echo ::set-output name=services::$(
          git submodule status -- services |
            jq \
              --raw-input \
              --null-input \
              --compact-output \
              '. |=
              [
                inputs | ltrimstr(" ") | split(" ") |
                {
                  sha:      .[0],
                  path:     .[1],
                  describe: .[2][1:-1]
                }
              ]'
        )

  build-services:
    needs: platform-info
    strategy:
      matrix:
        service: ${{ fromJson(needs.platform-info.outputs.services) }}
    runs-on: ubuntu-latest
    steps:
    - id: checkout-release
      uses: actions/checkout@v2
    - id: checkout-service
      run: git submodule init -- ${{ matrix.service.path }}
    - id: debug
      run: echo "::debug::${{ matrix.service.sha }}"
