name: Build

on:
  # Tempory manual dispatch for testing
  workflow_dispatch:
    inputs:
      version:
        description: 'Platform Version'
        required: true

jobs:
  platform-info:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.introspect.outputs.services }}
      commit: ${{ steps.introspect.outputs.commit }}
    name: Prepare
    steps:
    - name: Checkout release
      uses: actions/checkout@v2
    - name: Discover services
      id:   introspect
      run: |
        echo ::set-output name=commit::$(git rev-parse HEAD)
        echo ::set-output name=services::$(
          git submodule--helper list services |
          while read -r _ sha _ path; do
            sm_name=$(git submodule--helper name $path)
            name=$(basename $path)
            repo=$(git submodule--helper config submodule.$sm_name.url)
            echo "$name $path $repo $sha"
          done |
          jq -Rnc '. |= [ inputs | split(" ") |
            {
              name: .[0],
              path: .[1],
              repo: .[2],
              ref:  .[3]
            }
          ]'
        )

  build-services:
    needs: platform-info
    strategy:
      matrix:
        service: ${{ fromJson(needs.platform-info.outputs.services) }}
    runs-on: ubuntu-latest
    name: Build ${{ matrix.service.name }}
    steps:
    - uses: ./.github/action/build-service-image
      with:
        context: ${{ matrix.service.repo}}#${{ matrix.service.ref }}
        name:    ${{ matrix.service.name }}
        tag:     ${{ github.event.inputs.version }}
        commit:  ${{ need.platform-info.outputs.commit }}
