name: Build

on:
  # Tempory manual dispatch for testing
  workflow_dispatch:
    inputs:
      version:
        description: 'Platform Version'
        required: true

jobs:
  platform-info:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.introspect.outputs.services }}
    name: Prepare
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Discover services
      id:   introspect
      run: |
        echo ::set-output name=services::$(
          git submodule status -- services |
            jq -Rnc '. |= [ inputs[1:] | split(" ") |
              {
                name: .[1]|ltrimstr("services/"),
                sha:  .[0],
                path: .[1]
              }
            ]'
        )

  build-services:
    needs: platform-info
    strategy:
      matrix:
        service: ${{ fromJson(needs.platform-info.outputs.services) }}
    runs-on: ubuntu-latest
    name: Build ${{ matrix.service.name }}
    steps:
    - name: Checkout release repo
      uses: actions/checkout@v2
    - name: Checkout ${{ matrix.service.name }}
      run:  git submodule init -- ${{ matrix.service.path }}
    - name: debug
      run:  echo "::debug::${{ matrix.service.sha }}"
