name: Build

on:
  workflow_run:
    workflows: [Update]
    branches: [nightly]
    types: [completed]
  push:
    branches:
      - '[0-9].[0-9][0-9][0-9][0-9]'

jobs:
  platform-info:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.introspect.outputs.services }}
      commit: ${{ steps.introspect.outputs.commit }}
      version: ${{ steps.version.outputs.tag }}
    name: Prepare
    steps:
    - name: Checkout release
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
    - name: Generate version number
      id: version
      run: |
        branch=$(git branch --show-current)
        if [ $branch == "nightly" ]
        then
          echo ::set-output name=tag::$branch
        else
          offset=$(git rev-list nightly.. --count)
          echo ::set-output name=tag::placeos-$branch.$offset
        fi
    - name: Discover services
      id:   introspect
      run: |
        echo ::set-output name=commit::$(git rev-parse HEAD)
        echo ::set-output name=services::$(
          git submodule--helper list services |
          while read -r _ sha _ path; do
            sm_name=$(git submodule--helper name $path)
            name=$(basename $path)
            repo=$(git submodule--helper config submodule.$sm_name.url)
            echo "$name $path $repo $sha"
          done |
          jq -Rnc '. |= [ inputs | split(" ") |
            {
              name: .[0],
              path: .[1],
              repo: .[2],
              ref:  .[3]
            }
          ]'
        )

  build-services:
    needs: platform-info
    strategy:
      matrix:
        service: ${{ fromJson(needs.platform-info.outputs.services) }}
    runs-on: ubuntu-latest
    name: Build ${{ matrix.service.name }}
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id:   build
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.service.repo }}#${{ matrix.service.ref }}
        push: true
        tags: placeos/${{ matrix.service.name }}:${{ needs.platform-info.outputs.version }}
        build-args: PLACE_COMMIT=${{ needs.platform-info.outputs.commit }}
