name: Scan

on:
  schedule:
  - cron: "0 21 * * *"

  workflow_dispatch:

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.introspect.outputs.services }}
      version:  ${{ steps.introspect.outputs.version }}
    name: Discover
    steps:
    -
      name: Checkout local actions and scripts
      uses: actions/checkout@v2
    -
      name: Discover services
      id:   introspect
      uses: ./.github/actions/platform-info
      with:
        ref: ${{ github.ref }}

  scan:
    needs: discover
    strategy:
      matrix:
        service: ${{ fromJson(needs.discover.outputs.services) }}
        version:
        - ${{ needs.discover.outputs.version }}
      fail-fast: false
    runs-on: ubuntu-latest
    name: Scan ${{ matrix.service.name }}
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Pull
      run: docker pull placeos/${{ matrix.service.name }}:${{ matrix.version }}
    -
      name: Scan
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: placeos/${{ matrix.service.name }}:${{ matrix.version }}
        fail-build: true
        severity-cutoff: critical
        acs-report-enable: true
    -
      name: Report
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
        category: ${{ github.workflow }}/${{ github.job }}/${{ matrix.service.path }}/${{ matrix.version }}/${{ github.run_id }}
