name: Shard Report

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: [Update]
    branches: [nightly]
    types: [completed]

jobs:
  generate:
    runs-on: ubuntu-latest
    container: crystallang/crystal:1.1.1
    steps:
      -
        name: Checkout release
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      -
        name: Generate report
        run: |
          ./.scripts/query_shard_versions.cr . \
            action-controller \
            clustering \
            hound-dog \
            neuroplastic \
            opentelemetry-api \
            opentelemetry-instrumentation \
            placeos \
            placeos-compiler \
            placeos-core-client \
            placeos-driver \
            placeos-log-backend \
            placeos-models \
            placeos-resource \
            promise \
            rethinkdb \
            rethinkdb-orm > shard_report.md
      -
        name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: Shard Report
          path: shard_report.md
      -
        name: Show report
        run: cat shard_report.md
