name: Update

on:
  schedule:
  - cron: "0 15 * * *"

  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    name: Update submodules
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure git user
      run: |
        git config user.email "robots@place.technology"
        git config user.name "PlaceOS Robot"
    - name: Update
      run:  git submodule update --init --remote
    - name: Commit
      run: |
        git diff --name-only | xargs --max-args=1 --replace=PATH \
        git commit --message="chore: update PATH" PATH
    - name: Push
      run:  git push
