name: Update

on:
  workflow_dispatch:
  schedule:
  - cron: "0 18 * * *"

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    name: Update submodules
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure git as robot
      if:   github.event_name == 'schedule'
      run: |
        git config user.email robots@place.technology
        git config user.name PlaceOS Robot
    - name: Configure git as ${{ github.actor }}
      if:   github.event_name == 'workflow_dispatch'
      run: |
        git config user.email ${{ github.actor }}@users.noreply.github.com
        git config user.name ${{ github.actor }}
    - name: Update
      run:  git submodule update --init --remote
    - name: Commit
      run: |
        git diff --name-only | xargs --max-args=1 --replace=PATH \
        git commit --message="auto-pull PATH" PATH
    - name: Push
      run:  git push
