name: Update Monthly Release Branch

on:
  push:
    branches:
      - release

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git user
        run: |
          git config user.email "robots@place.technology"
          git config user.name "PlaceOS Robot"
      - name: Push changes to monthly branch
        shell: bash
        run: |
          set -x
          git fetch --all

          monthly_branch="$(sed -rE 's/^(placeos-)?([0-9\.]*)\.[0-9]+(-rc[0-9]+)?$/\2/' < VERSION)"

          echo "${monthly_branch}"

          git checkout "$monthly_branch" --track "origin/${monthly_branch}" || git checkout -b "$monthly_branch"
          git branch --set-upstream-to="origin/${monthly_branch}" "${monthly_branch}" || echo "branch not in remote"
          git merge --strategy-option=theirs release
          git push -u origin "$monthly_branch"
