name: Update Monthly Release Branch

on:
  push:
    branches:
      - release

env:
  EPHEMERAL_STAGING_BRANCH: placeos-ephemeral-staging

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure git user
        run: |
          git config user.email "robots@place.technology"
          git config user.name "PlaceOS Robot"
      - name: Push changes to monthly branch
        shell: bash
        run: |
          set -x

          version="$(cat VERSION)"
          monthly_branch="$(cat VERSION | sed -rE 's/^(placeos-)?([0-9\.]*)\.[0-9]+(-rc[0-9]+)?$/\2/')"
          git checkout -b ${{ env.EPHEMERAL_STAGING_BRANCH }}

          git checkout -b "$monthly_branch" || git checkout "$monthly_branch"

          git merge ${{ env.EPHEMERAL_STAGING_BRANCH }}
          git push -u origin "$monthly_branch"
