name: Update

on:
  workflow_dispatch:
  schedule:
  - cron: '* 10 * * *'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    name: Update submodules
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update
      run:  git submodule update --init --remote
    - name: Commit
      run: |
        git config user.email ${{ github.actor }}@users.noreply.github.com
        git config user.name ${{ github.actor }}
        git diff --name-only | xargs --max-args=1 --replace=PATH \
        git commit --message="auto-pull PATH" PATH
    - name: Push
      run:  git push
